[#153] Add json schema support on json inspection service
atlasmap/atlasmap-runtime pull request #154
Opened 2017-08-22 02:12 UTC by igarashitm

Added inspectJsonSchema() on JsonDocumentInspectionService to build a JsonDocument from json schema input

2017-08-22 07:00 UTC, rhuss requested changes
thanks, lgtm !

Some minor change requests below but close to being merged.

2017-08-22 07:00 UTC, rhuss commented on atlas-json-parent/atlas-json-core/src/main/java/io/atlasmap/json/inspect/SchemaInspector.java
> +            if (type == null || !type.asText().equals("object")) {
minor: probably not relevant here as `type.asText()` can not be `null` (?) but maybe a `!"object".equals(type.asText())` is safer here ?

2017-08-22 07:00 UTC, rhuss commented on atlas-json-parent/atlas-json-core/src/main/java/io/atlasmap/json/inspect/SchemaInspector.java
> +            Iterator<Entry<String, JsonNode>> topFields = rootNode.get("properties").fields();
NPE if there is no `properties` element, please check before (like for other fields)

2017-08-22 07:00 UTC, rhuss commented on atlas-json-parent/atlas-json-core/src/main/java/io/atlasmap/json/inspect/SchemaInspector.java
> +    public void inspect(String schema) throws JsonInspectionException {
What about making the inspect atomic with respect to generating the JsonDocument (would make it thread-safe, too). I.e. having a `JsonDocument inspect(String schema)` where the document itself is created within the method ?  The method then could even be `static`.

2017-08-22 07:00 UTC, rhuss commented on atlas-json-parent/atlas-json-core/src/main/java/io/atlasmap/json/inspect/SchemaInspector.java
> +        if (value.get("$ref") != null) {
Is this something we do need in the future ? (i.e. does the salesforce connector use `$ref` elements in the generated JSON schema ?) // @zregvart @dhirajsb

2017-08-22 07:00 UTC, rhuss commented on atlas-json-parent/atlas-json-core/src/main/java/io/atlasmap/json/inspect/SchemaInspector.java
> +            Iterator<Entry<String, JsonNode>> subFields = value.get("properties").fields();
`properties` might be missing in the value

2017-08-22 07:00 UTC, rhuss commented on atlas-json-parent/atlas-json-core/src/main/java/io/atlasmap/json/inspect/SchemaInspector.java
> +            answer = createJsonComplexType(name, value.get("items"), parent);
`value.get("items")` might be null, but this method assumes a not-null `value` element (see above). might be good to either check here for null, or above assert that `value` is not null.

2017-08-22 07:00 UTC, rhuss commented on atlas-json-parent/atlas-json-core/src/test/resources/inspect/schema/address.json
> +    "required": ["locality", "region", "country-name"],
I guess that `required` and `dependencies` properties are not used by the atlasmap mappings, right ?

2017-08-22 07:37 UTC, zregvart commented on atlas-json-parent/atlas-json-core/src/main/java/io/atlasmap/json/inspect/SchemaInspector.java
> +        if (value.get("$ref") != null) {
For results containing multiple objects (think search/query) it does use `$ref`, not sure if the Jackson JSON schema support might generate those on its own.

2017-08-22 14:01 UTC, merged

2017-08-22 14:26 UTC, igarashitm commented on atlas-json-parent/atlas-json-core/src/test/resources/inspect/schema/address.json
> +    "required": ["locality", "region", "country-name"],
I think so, at least the InstanceInspector doesn't care if it's required nor if there's any dependency in between. Possibly we may want to add it later. BTW these schema examples come from json-schema.org official - sorry I avoided to make something optimized for the tests as I'm lazy ;)
http://json-schema.org/examples.html

I submitted a follow-up PR #155 to reflect all review comments, thanks @rhuss , @zregvart !

2017-08-22 14:31 UTC, igarashitm commented on atlas-json-parent/atlas-json-core/src/main/java/io/atlasmap/json/inspect/SchemaInspector.java
> +        if (value.get("$ref") != null) {
I'm not sure how it's displayed in atlasmap-ui right now, but it definitely affects UI as well - inline all the nested objects? just show a link? like that

2017-08-23 07:20 UTC, rhuss commented
Oops, no ideas how I merged this PR. Strange ....

sorry ..., lets followup on #153

2017-08-23 07:21 UTC, rhuss commented
Maybe because is used "merged" in my comment ? (though the keyword was "[merge]" ....)